//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeshAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is continue pending.
        /// </summary>
        internal static string AgentIsContinuePending {
            get {
                return ResourceManager.GetString("AgentIsContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is disconnected.
        /// </summary>
        internal static string AgentIsDisconnected {
            get {
                return ResourceManager.GetString("AgentIsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is paused.
        /// </summary>
        internal static string AgentIsPaused {
            get {
                return ResourceManager.GetString("AgentIsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is pause pending.
        /// </summary>
        internal static string AgentIsPausePending {
            get {
                return ResourceManager.GetString("AgentIsPausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is running.
        /// </summary>
        internal static string AgentIsRunning {
            get {
                return ResourceManager.GetString("AgentIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is start pending.
        /// </summary>
        internal static string AgentIsStartPending {
            get {
                return ResourceManager.GetString("AgentIsStartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is stopped.
        /// </summary>
        internal static string AgentIsStopped {
            get {
                return ResourceManager.GetString("AgentIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is stopped pending.
        /// </summary>
        internal static string AgentIsStoppedPending {
            get {
                return ResourceManager.GetString("AgentIsStoppedPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent not installed.
        /// </summary>
        internal static string AgentNotInstalled {
            get {
                return ResourceManager.GetString("AgentNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        internal static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Help Request.
        /// </summary>
        internal static string CancelHelpRequest {
            get {
                return ResourceManager.GetString("CancelHelpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to server.
        /// </summary>
        internal static string ConnectedToServer {
            get {
                return ResourceManager.GetString("ConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Connect.
        /// </summary>
        internal static string DirectConnect {
            get {
                return ResourceManager.GetString("DirectConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from server and close?.
        /// </summary>
        internal static string DisconnectFromServerAndClose {
            get {
                return ResourceManager.GetString("DisconnectFromServerAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Green {
            get {
                object obj = ResourceManager.GetObject("Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Requested.
        /// </summary>
        internal static string HelpRequested {
            get {
                return ResourceManager.GetString("HelpRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to host: {0}..
        /// </summary>
        internal static string LockedToHost {
            get {
                return ResourceManager.GetString("LockedToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to server id: {0}..
        /// </summary>
        internal static string LockedToServerId {
            get {
                return ResourceManager.GetString("LockedToServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MeshCentral {
            get {
                object obj = ResourceManager.GetObject("MeshCentral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshCentral Assistant.
        /// </summary>
        internal static string MeshCentralAssistant {
            get {
                return ResourceManager.GetString("MeshCentralAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Users.
        /// </summary>
        internal static string MultipleUsers {
            get {
                return ResourceManager.GetString("MultipleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active remote sessions..
        /// </summary>
        internal static string NoActiveRemoteSessions {
            get {
                return ResourceManager.GetString("NoActiveRemoteSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No remote sessions.
        /// </summary>
        internal static string NoRemoteSessions {
            get {
                return ResourceManager.GetString("NoRemoteSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Activated (In).
        /// </summary>
        internal static string NotActivatedIn {
            get {
                return ResourceManager.GetString("NotActivatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Activated (Pre).
        /// </summary>
        internal static string NotActivatedPre {
            get {
                return ResourceManager.GetString("NotActivatedPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 remote session.
        /// </summary>
        internal static string OneRemoteSession {
            get {
                return ResourceManager.GetString("OneRemoteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 remote session is active..
        /// </summary>
        internal static string OneRemoteSessionIsActive {
            get {
                return ResourceManager.GetString("OneRemoteSessionIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string PNoneP {
            get {
                return ResourceManager.GetString("PNoneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red {
            get {
                object obj = ResourceManager.GetObject("Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Sessions: {0}.
        /// </summary>
        internal static string RemoteSessionsX {
            get {
                return ResourceManager.GetString("RemoteSessionsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Help.
        /// </summary>
        internal static string RequestHelp {
            get {
                return ResourceManager.GetString("RequestHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This executable is locked to only connect to {0}..
        /// </summary>
        internal static string SignedExecutableServerLockError {
            get {
                return ResourceManager.GetString("SignedExecutableServerLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP relay.
        /// </summary>
        internal static string TCPrelay {
            get {
                return ResourceManager.GetString("TCPrelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string TitleMerge {
            get {
                return ResourceManager.GetString("TitleMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP relay.
        /// </summary>
        internal static string UDPrelay {
            get {
                return ResourceManager.GetString("UDPrelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Assistant.
        /// </summary>
        internal static string XAssistant {
            get {
                return ResourceManager.GetString("XAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remote sessions.
        /// </summary>
        internal static string XRemoteSessions {
            get {
                return ResourceManager.GetString("XRemoteSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remote sessions are active..
        /// </summary>
        internal static string XRemoteSessionsAreActive {
            get {
                return ResourceManager.GetString("XRemoteSessionsAreActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow {
            get {
                object obj = ResourceManager.GetObject("Yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
